/*
 * File: app/model/Setting.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Dinmu.model.Setting', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field',
        'Ext.data.proxy.LocalStorage',
        'Ext.data.identifier.Uuid'
    ],

    config: {
        identifier: 'uuid',
        fields: [
            {
                name: 'id',
                type: 'auto'
            },
            {
                name: 'city',
                type: 'auto'
            },
            {
                name: 'country',
                type: 'auto'
            },
            {
                name: 'units',
                type: 'auto'
            },
            {
                name: 'geo',
                type: 'boolean'
            }
        ],
        validations: [
            {
                type: 'presence',
                message: 'Please provide a city',
                field: 'city'
            },
            {
                type: 'presence',
                message: 'Please provide a country',
                field: 'country'
            }
        ],
        proxy: {
            type: 'localstorage',
            id: 'weathersettings'
        }
    }
});