/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Dinmu.view.Main', {
    extend: 'Ext.carousel.Carousel',
    alias: 'widget.main',

    requires: [
        'Dinmu.view.SettingsView',
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.form.Panel',
        'Ext.Toolbar'
    ],

    config: {
        direction: 'vertical',
        items: [
            {
                xtype: 'titlebar',
                cls: 'title',
                docked: 'top',
                title: 'Do I need my  Umbrella?',
                items: [
                    {
                        xtype: 'button',
                        action: 'back',
                        cls: 'back',
                        hidden: true,
                        ui: 'back',
                        text: 'back'
                    },
                    {
                        xtype: 'button',
                        action: 'settings',
                        align: 'right',
                        ui: 'plain',
                        iconCls: 'settings',
                        text: ''
                    }
                ]
            },
            {
                xtype: 'settingsview'
            },
            {
                xtype: 'container',
                cls: 'textview',
                itemId: 'mainview'
            },
            {
                xtype: 'toolbar',
                cls: 'footer',
                docked: 'bottom',
                html: '<span>Powered by &copy; Sencha Touch</span>',
                ui: 'light'
            }
        ]
    }

});